# Usa uma imagem oficial do Node.js
FROM node:18-alpine

# Cria e define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependência
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código
COPY . .

# Expõe a porta (ajuste se necessário)
EXPOSE 3001

# Comando para iniciar com migração automática
CMD sh -c "npx sequelize db:create --config src/database/config/config.js 2>/dev/null || true && \
           npx sequelize db:migrate --config src/database/config/config.js --migrations-path src/database/migrations && \
           npm run dev"
