FROM node:18-alpine

WORKDIR /app

# Copia package.json e package-lock.json
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia restante da aplicação
COPY . .

EXPOSE 3001

CMD sh -c "npx sequelize db:create --config src/database/config/config.js 2>/dev/null || true && \
           npx sequelize db:migrate --config src/database/config/config.js --migrations-path src/database/migrations && \
           npm run dev"
